base_error: 実行中にエラーが発生しました。行：%s
receive: 受取：
process: 実行：
